### ISSUE TITLE
Thoughts on `gutenberg-metadata.json`

### ISSUE THREAD

**Issue by jaytula** [hugovk/gutenberg-metadata#15]
Feel free to disregard this and close this. I was just thinking and wanted to share... 😄 

`gutenberg-metadata.json` is pretty big and if you update it often, then the repository would become pretty big quickly.

You might have already thought of this... a potential workaround is to put it in another repository with just that one file. When updating the large file, empty the history or reset to the point before the large file was committed, commit the new large json, and force-push.

**Comment by jaytula** [comment]
Thanks! I'll have to look into artifacts/packages for my own edification.

**Comment by hugovk** [comment]
Oh and another option is zipping the file. Right now that 72 MB compresses down to a relatively compact ~10 MB.

**Comment by jaytula** [comment]
> Oh and another option is zipping the file. Right now that 72 MB compresses down to a relatively compact ~10 MB.

That occurred to me too. But it slightly inconveniences by having to unzip it. 

But it is a massive difference in file size would keep the status quo going for much longer than 4 years.

Initially I had no idea how big it was when downloading the `json` file but had it been a `zip` file, I probably at a glance would have hesitated to download it because it felt less ready to use and don't know right off the bat what is inside. I guess `json.zip` extension would be enough of a hint. Trivial concerns in the end.

I see you're a massive contributor to open source python and other stuff. Thanks for maintaining this small package.

**Comment by hugovk** [comment]
You're welcome!
